<a href="https://colab.research.google.com/github/vishal815/ANN-Regression-model-to-predict-the-electrical-energy-output-of-a-Combined-Cycle-Power-Plant/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import the libraries.
import numpy as np
import pandas as pd
import tensorflow as tf

1. Import the dataset

In [2]:
dataset=pd.read_excel('Folds5x2_pp.xlsx')
X=dataset.iloc[:, :-1].values         #created metric of features.
y=dataset.iloc[:,-1].values           #created dependent veriable vector.

In [3]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

2. Building the ANN

In [5]:
# Initializing the AAN
ann = tf.keras.models.Sequential()

In [6]:
# Adding the input layer and the hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [7]:
# Adding the second hidded layer.
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [8]:
# Adding the second hidden layer.
ann.add(tf.keras.layers.Dense(units=1))

3. Training the ANN.

In [9]:
# Complillng the ANN
ann.compile(optimizer= 'adam', loss='mean_squared_error')

In [10]:
# Training the ANN model on Training set.
ann.fit(X_train, y_train, batch_size=32, epochs= 100 )

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 208824.1250
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 206360.5938
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 206142.5312
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 205924.9375
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 205707.5000
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 205490.2031
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 205273.0781
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 205056.1875
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 204839.2812
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 204622.7188
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 204406.1406
Epoch 12/100
240/240 [===================

Predicting the results of the Test set

In [11]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[ 23.95 431.23]
 [ 23.95 460.01]
 [ 23.95 461.14]
 ...
 [ 23.95 473.26]
 [ 23.95 438.  ]
 [ 23.95 463.28]]
